name: Issue
description: Report a bug or request a feature
title: ""
body:
  - type: dropdown
    id: type
    attributes:
      label: Type
      options:
        - Bug
        - Feature Request
        - Question
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Briefly describe the issue or request.
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: Required for bugs.
