<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <UseUwp>true</UseUwp>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>GlueDock.DesktopOverlayWidget</AssemblyName>
    <RootNamespace>GlueDock.DesktopOverlayWidget</RootNamespace>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <OutputPath>..\bin\$(Configuration)\net10.0-windows10.0.19041.0\GlueDock_Widgets\GlueDock.DesktopOverlayWidget\</OutputPath>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\GlueDock.WidgetApi\GlueDock.WidgetApi.csproj">
      <Private>false</Private>
    </ProjectReference>
  </ItemGroup>

  <ItemGroup>
    <Using Remove="System.Drawing" />
    <Using Remove="System.Windows.Forms" />
  </ItemGroup>
</Project>
