<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseUwp>true</UseUwp>
    <UseUwpTools>false</UseUwpTools>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>GlueDock.ClockWidget</AssemblyName>
    <RootNamespace>GlueDock.ClockWidget</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\GlueDock.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Sounds\**\*.mp3">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
